name: obdet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - brotli=1.0.9=he6710b0_2
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_2
  - cfitsio=3.470=hf0d0db6_6
  - charls=2.2.0=h2531618_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - faiss=1.7.1=py39cuda112h5ca99f2_1_cuda
  - faiss-gpu=1.7.1=h788eb59_1
  - ffmpeg=4.3=hf484d3e_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - imagecodecs=2021.8.26=py39h4cda21f_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jxrlib=1.1=h7b6447c_2
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libblas=3.9.0=11_linux64_mkl
  - libcurl=7.80.0=h0b77cf5_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libfaiss=1.7.1=cuda112h5bea7ad_1_cuda
  - libfaiss-avx2=1.7.1=cuda112h1234567_1_cuda
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=11_linux64_mkl
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=0.2.1=py39h06a4308_1
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.1.1=py39h6323ea4_4
  - readline=8.1=h27cfd23_0
  - scikit-image=0.18.3=py39h51133e4_0
  - scikit-learn=1.0.1=py39h51133e4_0
  - scipy=1.7.1=py39h292c36d_2
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.36.0=hc218d9a_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.15.0
    - adal==1.2.7
    - addict==2.4.0
    - aiohttp==3.7.4.post0
    - alembic==1.7.7
    - argcomplete==1.12.3
    - arrow==1.2.2
    - async-timeout==3.0.1
    - attrs==21.2.0
    - autopage==0.5.0
    - azure-common==1.1.28
    - azure-core==1.21.1
    - azure-graphrbac==0.61.1
    - azure-identity==1.7.0
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==8.2.0
    - azure-mgmt-core==1.3.0
    - azure-mgmt-keyvault==9.3.0
    - azure-mgmt-resource==20.1.0
    - azure-mgmt-storage==19.1.0
    - azureml==0.2.7
    - azureml-core==1.39.0.post1
    - azureml-dataprep==2.27.1
    - azureml-dataprep-native==38.0.0
    - azureml-dataprep-rslex==2.3.1
    - azureml-dataset-runtime==1.39.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==3.2.0
    - boto3==1.20.44
    - botocore==1.23.44
    - bravado==11.0.3
    - bravado-core==5.17.0
    - cachetools==4.2.4
    - cffi==1.15.0
    - chardet==4.0.0
    - charset-normalizer==2.0.7
    - click==8.0.3
    - cliff==3.10.1
    - cmaes==0.8.2
    - cmd2==2.4.0
    - colorama==0.4.4
    - colorlog==6.6.0
    - contextlib2==21.6.0
    - cryptography==36.0.2
    - cycler==0.10.0
    - decorator==4.4.2
    - distro==1.7.0
    - docker==5.0.3
    - docopt==0.6.2
    - dotnetcore2==2.1.23
    - fqdn==1.5.1
    - fsspec==2021.10.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - google-auth==2.3.0
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.41.0
    - humanfriendly==10.0
    - idna==3.3
    - imageio==2.10.2
    - imageio-ffmpeg==0.4.5
    - infomap==2.2.0
    - isodate==0.6.1
    - isoduration==20.11.0
    - jeepney==0.7.1
    - jmespath==0.10.0
    - jsonpickle==1.5.2
    - jsonpointer==2.2
    - jsonref==0.2
    - jsonschema==4.4.0
    - kiwisolver==1.3.2
    - knack==0.9.0
    - lightning-bolts==0.4.0
    - mako==1.2.0
    - markdown==3.3.4
    - markupsafe==2.1.1
    - mmcv==1.4.7
    - monotonic==1.6
    - moviepy==1.0.3
    - msal==1.17.0
    - msal-extensions==0.3.1
    - msgpack==1.0.3
    - msrest==0.6.21
    - msrestazure==0.6.4
    - multidict==5.2.0
    - munch==2.5.0
    - ndg-httpsclient==0.5.1
    - neptune-client==0.14.2
    - oauthlib==3.1.1
    - opencv-python==4.5.5.64
    - optuna==2.10.0
    - pandas==1.3.4
    - paramiko==2.10.3
    - pathspec==0.9.0
    - pbr==5.8.1
    - pkginfo==1.8.2
    - portalocker==2.4.0
    - prettytable==3.2.0
    - proglog==0.1.9
    - protobuf==3.19.0
    - psutil==5.9.0
    - py-cpuinfo==8.0.0
    - pyarrow==3.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydeprecate==0.3.1
    - pygments==2.11.2
    - pyjwt==2.3.0
    - pynacl==1.5.0
    - pyopenssl==21.0.0
    - pyperclip==1.8.2
    - pyrsistent==0.18.1
    - pysocks==1.7.1
    - pytorch-lightning==1.4.9
    - pytorch-lightning-bolts==0.3.2
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rfc3339-validator==0.1.4
    - rfc3987==1.3.8
    - rsa==4.7.2
    - s3transfer==0.5.0
    - sacred==0.8.2
    - secretstorage==3.3.1
    - simplejson==3.17.6
    - smmap==5.0.0
    - sqlalchemy==1.4.35
    - stevedore==3.5.0
    - strict-rfc3339==0.7
    - swagger-spec-validator==2.7.4
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - timm==0.4.12
    - torchmetrics==0.5.1
    - tqdm==4.62.3
    - uri-template==1.1.0
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webcolors==1.11.1
    - websocket-client==1.2.3
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - yapf==0.32.0
    - yarl==1.7.0
prefix: /anaconda/envs/obdet
